<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = $this->productsData();

        foreach ($products as $data) {
            $category = Category::where('name', $data['category'])->first();
            if (!$category) {
                continue;
            }

            $slug = Str::slug($data['name']);
            // Ensure unique slug
            $baseSlug = $slug;
            $i = 1;
            while (Product::where('slug', $slug)->exists()) {
                $slug = $baseSlug . '-' . $i++;
            }

            $sku = strtoupper(Str::random(3)) . '-' . rand(1000, 9999);
            while (Product::where('sku', $sku)->exists()) {
                $sku = strtoupper(Str::random(3)) . '-' . rand(1000, 9999);
            }

            Product::firstOrCreate(
                ['name' => $data['name']],
                [
                    'slug'        => $slug,
                    'sku'         => $sku,
                    'description' => $data['description'],
                    'price'       => $data['price'],
                    'stock'       => rand(50, 100),
                    'category_id' => $category->id,
                    'image'       => 'https://picsum.photos/seed/' . urlencode($data['name']) . '/640/480',
                    'rating'      => $data['rating'],
                    'status'      => 'active',
                ]
            );
        }
    }

    private function productsData(): array
    {
        return [
            // ── Electronics ──────────────────────────────────────────────
            [
                'category'    => 'Electronics',
                'name'        => 'Sony Bravia 55" 4K Smart TV',
                'description' => '4K HDR OLED display with Google TV, Dolby Vision, and HDMI 2.1 ports for the ultimate home cinema experience.',
                'price'       => 1299.99,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'JBL Charge 5 Bluetooth Speaker',
                'description' => 'Portable waterproof Bluetooth speaker with 20-hour battery life, deep bass, and built-in power bank.',
                'price'       => 179.99,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'Logitech G502 X Gaming Mouse',
                'description' => 'High-performance wired gaming mouse with LIGHTFORCE hybrid switches, 25600 DPI HERO 2 sensor.',
                'price'       => 79.99,
                'rating'      => 4.8,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'Keychron K2 Mechanical Keyboard',
                'description' => 'Compact 75% wireless mechanical keyboard with Gateron switches, hot-swappable PCB and RGB backlight.',
                'price'       => 109.00,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'LG 27GP850-B Monitor 165Hz',
                'description' => '27" QHD Nano IPS gaming monitor, 165Hz refresh rate, 1ms GTG response time and NVIDIA G-Sync compatible.',
                'price'       => 449.99,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'Samsung T7 Shield 2TB SSD',
                'description' => 'Ruggedized portable SSD with USB 3.2 Gen 2 interface, up to 1050 MB/s read speed and IP65 rating.',
                'price'       => 149.99,
                'rating'      => 4.8,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'Anker 12-in-1 USB-C Hub',
                'description' => 'Expand connectivity with 2× HDMI 4K, 3× USB-A 3.0, SD/microSD reader, and 100W PD pass-through.',
                'price'       => 69.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'Logitech C920 Pro HD Webcam',
                'description' => 'Full HD 1080p/30fps streaming webcam with dual stereo mics and automatic light correction.',
                'price'       => 89.99,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'Amazon Echo (4th Gen)',
                'description' => 'Smart speaker with premium sound, Alexa voice assistant, and smart home hub built in.',
                'price'       => 99.99,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'GoPro HERO12 Black Action Camera',
                'description' => '5.3K60 video, HyperSmooth 6.0 stabilization, waterproof to 33ft without a housing, and auto upload.',
                'price'       => 399.99,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'DJI Mini 4 Pro Drone',
                'description' => 'Sub-249g foldable drone with 4K/60fps camera, 34-min flight time, and obstacle sensing in 4 directions.',
                'price'       => 759.00,
                'rating'      => 4.9,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'TP-Link Archer AXE75 Router',
                'description' => 'Tri-band WiFi 6E router, 6 GHz band, 4804 Mbps AX speed, MU-MIMO and 4× gigabit LAN ports.',
                'price'       => 219.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'Ring Video Doorbell Pro 2',
                'description' => 'Head-to-Toe HD+ video, 3D motion detection, dual-band Wi-Fi and colour pre-roll capture.',
                'price'       => 249.99,
                'rating'      => 4.3,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'Philips Hue White & Colour LED Starter Kit',
                'description' => 'Smart lighting kit with 4 A19 bulbs, Hue Bridge, 16 million colours, voice and app control.',
                'price'       => 139.99,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'Sony WF-1000XM5 True Wireless Earbuds',
                'description' => 'Industry-leading noise cancellation, 8-hour battery (24h with case), LDAC and multipoint Bluetooth.',
                'price'       => 299.99,
                'rating'      => 4.8,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'Dyson V15 Detect Absolute Vacuum',
                'description' => 'Laser dust detection, HEPA filtration, 60-minute fade-free power and 14 attachments included.',
                'price'       => 749.99,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'Instant Pot Duo 7-in-1 6QT',
                'description' => 'Multi-cooker with pressure cooker, slow cooker, rice cooker, steamer, sauté, yogurt maker functions.',
                'price'       => 89.95,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'Blink Outdoor Security Camera 4-Pack',
                'description' => 'Wireless HD outdoor security cameras with 2-year battery life, motion alerts and Alexa integration.',
                'price'       => 189.99,
                'rating'      => 4.2,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'Braun Series 9 Pro Electric Shaver',
                'description' => 'Intelligent AutoSense technology, 5-sync cutting system, SmartCare center with auto-clean and charge.',
                'price'       => 349.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Electronics',
                'name'        => 'Dyson Pure Cool Air Purifier Fan',
                'description' => 'HEPA+Carbon filtration, 350° oscillation, real-time air quality report and 10 airflow settings.',
                'price'       => 549.99,
                'rating'      => 4.4,
            ],

            // ── Laptops ──────────────────────────────────────────────────
            [
                'category'    => 'Laptops',
                'name'        => 'Apple MacBook Pro 14" M3 Pro',
                'description' => 'Apple M3 Pro chip, 18GB unified memory, 512GB SSD, Liquid Retina XDR display and 22-hour battery.',
                'price'       => 1999.00,
                'rating'      => 4.9,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'Dell XPS 15 9530',
                'description' => 'Intel Core i7-13700H, 32GB DDR5, RTX 4060, 15.6" OLED touch display and Thunderbolt 4 connectivity.',
                'price'       => 2199.99,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'Lenovo ThinkPad X1 Carbon Gen 11',
                'description' => 'Ultra-light 1.12kg business laptop, Intel vPro Core i7, 16GB LPDDR5, 14" IPS anti-glare display.',
                'price'       => 1749.00,
                'rating'      => 4.8,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'HP Spectre x360 14',
                'description' => 'OLED 2.8K touch 2-in-1, Intel Core Ultra 7, 16GB RAM, 512GB SSD and Intel Arc graphics.',
                'price'       => 1649.99,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'ASUS ZenBook Pro Duo 15 OLED',
                'description' => 'Dual display 4K OLED laptop with RTX 4060, ScreenPad Plus secondary display and Intel i9-13900H.',
                'price'       => 2499.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'Microsoft Surface Laptop 5',
                'description' => '13.5" PixelSense touch display, Intel Core i5-1235U, 8GB RAM, 512GB SSD, up to 18-hour battery.',
                'price'       => 1299.99,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'Razer Blade 15 Gaming Laptop',
                'description' => '15.6" QHD 240Hz display, Intel Core i7-13800H, RTX 4070, 16GB DDR5, per-key RGB keyboard.',
                'price'       => 2799.99,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'Acer Swift 5 SF514',
                'description' => 'Ultra-thin 985g laptop, Intel Core i5-1340P, 16GB LPDDR5, 14" 2K IPS display and Thunderbolt 4.',
                'price'       => 999.99,
                'rating'      => 4.3,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'LG Gram 17 2023',
                'description' => '17" WQXGA IPS display, Intel EVO Core i7, 16GB, 512GB, military-grade MIL-STD-810H and 21-hour battery.',
                'price'       => 1699.99,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'ASUS ROG Strix SCAR 16',
                'description' => '16" QHD+ 240Hz ROG Nebula HDR display, Intel Core i9-13980HX, RTX 4090, 32GB DDR5.',
                'price'       => 3499.99,
                'rating'      => 4.8,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'HP Pavilion 15 2023',
                'description' => 'Everyday laptop with Intel Core i5-1335U, 8GB RAM, 512GB SSD, FHD IPS display and HP Fast Charge.',
                'price'       => 649.99,
                'rating'      => 4.2,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'Lenovo IdeaPad 5 Pro 14',
                'description' => '2.8K OLED 90Hz display, AMD Ryzen 7 7735U, 16GB, 512GB, Dolby Atmos audio and 68Wh battery.',
                'price'       => 849.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'Samsung Galaxy Book3 360',
                'description' => '13.3" Super AMOLED 2-in-1, Intel Core i7-1360P, 16GB, 512GB, Galaxy ecosystem integration.',
                'price'       => 1149.99,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'MSI Prestige 16 Studio',
                'description' => 'Creator laptop with 16" 4K display, Intel Core i7-13700H, RTX 4060, 32GB DDR5 and True Pixel display.',
                'price'       => 1899.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'Huawei MateBook X Pro 2023',
                'description' => '14.2" 3.1K OLED multi-touch, Intel Core i7-1360P, 16GB, 1TB, 60W USB-C fast charge.',
                'price'       => 1399.99,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'Acer Predator Helios 16',
                'description' => '16" WQXGA 240Hz mini-LED, Intel Core i9-13900HX, RTX 4080, 32GB DDR5, LiquidMetal thermal paste.',
                'price'       => 3199.99,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'Toshiba Portégé Z30-E',
                'description' => 'Enterprise ultra-mobile, Intel Core i7, 16GB, 512GB SSD, 13.3" FHD, weighs just 1.04kg.',
                'price'       => 1449.00,
                'rating'      => 4.2,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'Dell Inspiron 15 3000',
                'description' => 'Budget-friendly 15.6" FHD laptop, Intel Core i5, 8GB RAM, 256GB SSD and Windows 11 Home.',
                'price'       => 499.99,
                'rating'      => 4.0,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'ASUS VivoBook 15 OLED',
                'description' => '15.6" FHD OLED display, Intel Core i5-12500H, 16GB, 512GB SSD, ASUS NumberPad and ErgoSense keyboard.',
                'price'       => 799.99,
                'rating'      => 4.3,
            ],
            [
                'category'    => 'Laptops',
                'name'        => 'Gigabyte Aero 16 OLED BSF',
                'description' => '16" Samsung OLED X-Rite Pantone calibrated, Intel Core i9-13900H, RTX 4080, 32GB DDR5.',
                'price'       => 2999.99,
                'rating'      => 4.6,
            ],

            // ── Smartphones ──────────────────────────────────────────────
            [
                'category'    => 'Smartphones',
                'name'        => 'Apple iPhone 15 Pro',
                'description' => 'Titanium design, A17 Pro chip, 48MP main camera with optical zoom, Action button and USB-C.',
                'price'       => 999.00,
                'rating'      => 4.8,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'Samsung Galaxy S24 Ultra',
                'description' => 'Snapdragon 8 Gen 3, 200MP camera, built-in S Pen, 5000mAh battery and 12GB/256GB.',
                'price'       => 1299.99,
                'rating'      => 4.9,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'Google Pixel 8 Pro',
                'description' => 'Google Tensor G3, 50MP triple camera, 6.7" LTPO OLED, 7 years OS support and temperature sensor.',
                'price'       => 999.00,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'OnePlus 12',
                'description' => 'Snapdragon 8 Gen 3, Hasselblad 50MP camera, 100W SuperVOOC charging, 5400mAh battery.',
                'price'       => 799.00,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'Samsung Galaxy A54 5G',
                'description' => '6.4" Super AMOLED, 50MP OIS camera, Exynos 1380, 5000mAh, 4 years of OS updates.',
                'price'       => 449.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'Xiaomi 14',
                'description' => 'Snapdragon 8 Gen 3, Leica 50MP camera, 3200-nit LTPO OLED, 90W HyperCharge, 4610mAh.',
                'price'       => 849.00,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'Sony Xperia 1 V',
                'description' => 'Zeiss 52MP triple camera, 4K 120Hz OLED display, Snapdragon 8 Gen 2, 3.5mm headphone jack.',
                'price'       => 1199.00,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'OPPO Find X7 Ultra',
                'description' => 'Dual periscope camera system, 50MP × 4 quad camera, 100W SuperVOOC, 5000mAh, MediaTek Dimensity 9300.',
                'price'       => 1099.00,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'Nothing Phone 2',
                'description' => 'Transparent Glyph Interface, Snapdragon 8+ Gen 1, 50MP dual camera, 4700mAh and clean Android.',
                'price'       => 699.00,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'Motorola Edge 40 Pro',
                'description' => '165Hz OLED, Snapdragon 8 Gen 2, 50MP triple camera, 125W TurboPower charging, IP68 rated.',
                'price'       => 599.99,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'Apple iPhone SE (3rd Gen)',
                'description' => 'A15 Bionic chip, 4.7" Retina HD display, 12MP camera, Touch ID and 5G connectivity.',
                'price'       => 429.00,
                'rating'      => 4.3,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'ASUS ROG Phone 7 Ultimate',
                'description' => 'Snapdragon 8 Gen 2, 165Hz AMOLED, AeroActive Cooler 7, 6000mAh, 65W charging, gaming triggers.',
                'price'       => 1099.99,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'Honor Magic6 Pro',
                'description' => '5800mAh silicon-carbon battery, 180MP periscope camera, Snapdragon 8 Gen 3, 100W wired charging.',
                'price'       => 899.00,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'Realme GT 5 Pro',
                'description' => '6.78" BOE LTPO OLED 144Hz, Snapdragon 8 Gen 3, 50MP Sony LYT-808, 5400mAh 100W charging.',
                'price'       => 649.00,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'Apple iPhone 14',
                'description' => 'A15 Bionic, 6.1" Super Retina XDR, 12MP dual camera, Crash Detection and Emergency SOS via satellite.',
                'price'       => 699.00,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'Samsung Galaxy M54 5G',
                'description' => '108MP triple camera, 5000mAh with 25W fast charge, Exynos 1380, 120Hz Super AMOLED Plus.',
                'price'       => 379.99,
                'rating'      => 4.2,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'Vivo X100 Pro',
                'description' => 'Zeiss 1-inch main sensor, 4.5-inch periscope zoom, Dimensity 9300, 5400mAh 100W FlashCharge.',
                'price'       => 949.00,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'Nokia X30 5G',
                'description' => 'Penta-lens 50MP PureView camera, Snapdragon 695 5G, 4200mAh, recycled aluminium body and Android One.',
                'price'       => 349.99,
                'rating'      => 4.0,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'Huawei P60 Pro',
                'description' => 'Variable aperture Leica camera, Kirin 9200+, 4815mAh 88W fast charging, IP68 water resistant.',
                'price'       => 999.00,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Smartphones',
                'name'        => 'Samsung Galaxy S24',
                'description' => 'Snapdragon 8 Gen 3 for Galaxy, 50MP triple camera, 6.2" Dynamic AMOLED, 7 years OS support.',
                'price'       => 799.99,
                'rating'      => 4.7,
            ],

            // ── Smartwatches ──────────────────────────────────────────────
            [
                'category'    => 'Smartwatches',
                'name'        => 'Apple Watch Series 9 GPS 45mm',
                'description' => 'S9 SiP chip, double tap gesture, always-on Retina display, health sensors and carbon neutral.',
                'price'       => 429.00,
                'rating'      => 4.8,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'Samsung Galaxy Watch 6 Classic 47mm',
                'description' => 'Rotating bezel, 1.5" Super AMOLED, Exynos W930, BioActive sensor and Google Wear OS.',
                'price'       => 399.99,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'Garmin Fenix 7 Solar',
                'description' => 'Multi-sport GPS, solar charging lens, topographic maps, 18-day battery and titanium bezel.',
                'price'       => 749.99,
                'rating'      => 4.8,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'Fitbit Sense 2',
                'description' => 'ECG, skin conductance stress sensor, SpO2, sleep tracking, 6-day battery and Amazon Alexa.',
                'price'       => 249.95,
                'rating'      => 4.3,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'Amazfit GTR 4',
                'description' => 'Alexa built-in, 150+ sports modes, 14-day battery, GPS dual-band and Zepp OS.',
                'price'       => 199.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'Google Pixel Watch 2',
                'description' => 'Wear OS 4, Fitbit advanced health tracking, Snapdragon W5 Gen 1, 24-hour battery and ECG.',
                'price'       => 349.99,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'Polar Vantage V3',
                'description' => 'Dual-frequency GPS, optical ECG, 140+ sport profiles, 43-hour GPS battery and sapphire glass.',
                'price'       => 699.95,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'COROS APEX 2 Pro',
                'description' => 'Multi-band GPS, 75-hour GPS mode, sapphire crystal, offline music and exclusive TrailRun mode.',
                'price'       => 499.99,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'Huawei Watch GT4 46mm',
                'description' => 'Two-week battery, 100+ workout modes, TruSeen 5.5+ heart rate, SpO2 and irregular heartbeat detection.',
                'price'       => 299.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'Apple Watch Ultra 2',
                'description' => 'Titanium case, 49mm, precision dual-frequency GPS, 60-hour battery with low power mode.',
                'price'       => 799.00,
                'rating'      => 4.9,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'Withings ScanWatch 2',
                'description' => 'Medical-grade ECG, SpO2, sleep apnoea detection, 30-day battery and hybrid analog display.',
                'price'       => 349.95,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'Garmin Forerunner 955 Solar',
                'description' => 'Running dynamics, full-colour maps, training load focus, 20-day solar battery and race predictor.',
                'price'       => 599.99,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'Fossil Gen 6 Wellness',
                'description' => 'Wear OS 3.5, SpO2, heart rate, Alexa, 3-day battery and stainless steel case.',
                'price'       => 229.00,
                'rating'      => 4.1,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'Mobvoi TicWatch Pro 5',
                'description' => 'Snapdragon W5+ Gen 1, 80-hour battery with smart mode, 144+ sports modes and 5ATM water resistance.',
                'price'       => 349.99,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'Suunto Vertical',
                'description' => 'Titanium bezel, 60-day battery, offline maps with global heatmaps, dual-frequency GPS.',
                'price'       => 649.00,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'OnePlus Watch 2',
                'description' => 'Wear OS 4, Snapdragon W5 + BES2700, 100-hour battery, AMOLED display and 110+ sports modes.',
                'price'       => 299.00,
                'rating'      => 4.3,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'Xiaomi Watch S2 46mm',
                'description' => '1.43" AMOLED, Zepp OS, 117+ workout modes, 12-day battery and Bluetooth 5.2.',
                'price'       => 199.99,
                'rating'      => 4.2,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'Samsung Galaxy Watch 5 Pro',
                'description' => 'Titanium case, sapphire glass, 80-hour extended battery mode, Wear OS and track back navigation.',
                'price'       => 329.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'Garmin Venu 3',
                'description' => 'Super bright AMOLED, wheelchair mode, nap detection, sleep coaching, 14-day battery life.',
                'price'       => 449.99,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Smartwatches',
                'name'        => 'Fitbit Charge 6',
                'description' => 'Built-in GPS, Google Maps & Wallet integration, ECG, SpO2 and 7-day battery life.',
                'price'       => 159.95,
                'rating'      => 4.3,
            ],

            // ── Tablets ──────────────────────────────────────────────────
            [
                'category'    => 'Tablets',
                'name'        => 'Apple iPad Pro 12.9" M2',
                'description' => 'M2 chip, Liquid Retina XDR mini-LED display, ProMotion 120Hz, Thunderbolt 4 and Wi-Fi 6E.',
                'price'       => 1099.00,
                'rating'      => 4.9,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'Apple iPad Air (5th Gen)',
                'description' => 'M1 chip, 10.9" Liquid Retina, 5G capable, USB-C, Touch ID in top button and Center Stage.',
                'price'       => 599.00,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'Samsung Galaxy Tab S9 Ultra',
                'description' => '14.6" Dynamic AMOLED 2X, Snapdragon 8 Gen 2, 12GB/256GB, IP68, included S Pen and DeX mode.',
                'price'       => 1199.99,
                'rating'      => 4.8,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'Microsoft Surface Pro 9',
                'description' => '13" PixelSense Flow display 120Hz, Intel Core i5/i7 or Microsoft SQ3, detachable keyboard ready.',
                'price'       => 1299.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'Amazon Fire Max 11',
                'description' => '11" 2000×1200 display, 14-hour battery, 64GB with microSD, USB-C and optional keyboard folio.',
                'price'       => 229.99,
                'rating'      => 4.3,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'Lenovo Tab P12',
                'description' => '12.7" 3K IPS display, MediaTek Dimensity 7050, 8GB/128GB, four-speaker system and 10200mAh.',
                'price'       => 499.99,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'Xiaomi Pad 6 Pro',
                'description' => '11" 144Hz 2.8K display, Snapdragon 8+ Gen 1, 8GB/256GB, quad speakers and 67W fast charge.',
                'price'       => 549.99,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'ASUS ROG Flow Z13',
                'description' => 'Gaming 2-in-1 tablet, Intel Core i9-13900H, RTX 4060, 13.4" 165Hz display and XG Mobile port.',
                'price'       => 2299.99,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'Huawei MatePad Pro 11',
                'description' => 'OLED 144Hz display, Kirin 9000E, 8GB/256GB, M-Pencil 2nd gen support and HarmonyOS 3.',
                'price'       => 749.00,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'Apple iPad Mini (6th Gen)',
                'description' => '8.3" Liquid Retina display, A15 Bionic, 5G, USB-C, Touch ID and Apple Pencil 2nd gen support.',
                'price'       => 499.00,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'Samsung Galaxy Tab S8+',
                'description' => '12.4" Super AMOLED 120Hz, Snapdragon 8 Gen 1, DeX mode, included S Pen and IP68 rated.',
                'price'       => 899.99,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'Amazon Fire HD 10 Plus',
                'description' => '10.1" 1080p Full HD, wireless charging, 12-hour battery, 4GB RAM and 64GB expandable storage.',
                'price'       => 179.99,
                'rating'      => 4.2,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'Google Pixel Tablet',
                'description' => 'Google Tensor G2, 11" LCD 60Hz, charging speaker dock included, hub mode for smart home control.',
                'price'       => 499.00,
                'rating'      => 4.2,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'OnePlus Pad',
                'description' => '11.61" 144Hz LCD, MediaTek Dimensity 9000, 12GB/256GB, 67W SUPERVOOC and 13MP camera.',
                'price'       => 479.99,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'Apple iPad (10th Gen)',
                'description' => '10.9" Liquid Retina, A14 Bionic, USB-C, 5G, landscape front camera for Centre Stage.',
                'price'       => 449.00,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'Lenovo Tab Extreme',
                'description' => '14.5" 3K OLED 120Hz, MediaTek Dimensity 9000, 12GB/256GB, JBL quad speakers and 10200mAh.',
                'price'       => 799.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'Nokia T21',
                'description' => '10.4" 2K display, UNISOC T612, 4GB/64GB, 8200mAh battery and 3 years security updates.',
                'price'       => 219.99,
                'rating'      => 3.9,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'TCL Tab 10s 5G',
                'description' => '10.1" FHD display, Snapdragon 480, 4GB/64GB, quad speakers and dual SIM 5G connectivity.',
                'price'       => 249.99,
                'rating'      => 3.8,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'Realme Pad X',
                'description' => '11" 2K display, Snapdragon 695, 6GB/128GB, 8340mAh 33W fast charging and Dolby Atmos.',
                'price'       => 329.99,
                'rating'      => 4.1,
            ],
            [
                'category'    => 'Tablets',
                'name'        => 'Blackview Tab 16',
                'description' => '11" 2K display, MediaTek MT8183, 8GB/256GB, Android 12, 7680mAh and 4G LTE.',
                'price'       => 199.99,
                'rating'      => 3.8,
            ],

            // ── Headphones & Headsets ─────────────────────────────────────
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'Sony WH-1000XM5',
                'description' => 'Industry-leading ANC, 30-hour battery, multipoint Bluetooth, LDAC and speak-to-chat feature.',
                'price'       => 349.99,
                'rating'      => 4.9,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'Bose QuietComfort 45',
                'description' => 'World-class noise cancellation, TriPort acoustic architecture, 24-hour battery and Aware mode.',
                'price'       => 279.99,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'Apple AirPods Max',
                'description' => 'H1 chip ANC, Transparency mode, spatial audio with head tracking, 20-hour battery.',
                'price'       => 549.00,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'Jabra Evolve2 85',
                'description' => 'Professional UC headset, 8-mic ANC, 37-hour battery, FlexBoom mic and smart control app.',
                'price'       => 449.00,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'Sennheiser Momentum 4 Wireless',
                'description' => 'Adaptive ANC, 60-hour battery, customizable sound via EQ, USB-C and Bluetooth 5.2.',
                'price'       => 349.95,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'Audio-Technica ATH-M50xBT2',
                'description' => 'Studio-quality sound, multipoint Bluetooth, 50-hour battery, touch controls and foldable design.',
                'price'       => 179.00,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'Beyerdynamic DT 700 Pro X',
                'description' => 'Closed-back studio headphone, 48Ω STELLAR.45 driver, replaceable ear pads and velour cushions.',
                'price'       => 299.00,
                'rating'      => 4.8,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'Anker Soundcore Q45',
                'description' => 'Adaptive ANC, 40-hour battery, LDAC HiRes audio, foldable and multipoint connection.',
                'price'       => 79.99,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'JBL Tour One M2',
                'description' => 'True Adaptive ANC, 30-hour battery, Personi-Fi 2.0 personalization and Bluetooth 5.3.',
                'price'       => 349.95,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'Razer Kraken V3 HyperSense',
                'description' => 'Haptic technology wired gaming headset, HyperSense vibration, TriForce Titanium drivers, RGB.',
                'price'       => 129.99,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'SteelSeries Arctis Nova Pro Wireless',
                'description' => 'Dual-wireless (2.4GHz + Bluetooth), hot-swap battery, ANC, Hi-Res audio and GameDAC Gen 2.',
                'price'       => 349.99,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'HyperX Cloud Alpha Wireless',
                'description' => '300-hour battery, dual-chamber drivers, 2.4GHz wireless, 50mm neodymium drivers.',
                'price'       => 199.99,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'Corsair Virtuoso RGB Wireless XT',
                'description' => 'Hi-Res audio certified, Slipstream 2.4GHz wireless, 24-hour battery, 50mm neodymium drivers.',
                'price'       => 219.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'Plantronics Voyager Focus 2',
                'description' => 'UC certified stereo headset, 19-hour talk time, Active ANC, Bluetooth 5.1 and smart sensor.',
                'price'       => 309.99,
                'rating'      => 4.3,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'Logitech H800 Wireless Headset',
                'description' => 'Multi-device pairing (Bluetooth + USB), 6-hour battery, 360° mic and plug-and-play nano receiver.',
                'price'       => 99.99,
                'rating'      => 4.0,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'AKG K371 Closed-Back Headphones',
                'description' => 'Reference closed-back studio headphone, 40mm titanium-coated drivers, foldable and 3 cable options.',
                'price'       => 149.00,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'Turtle Beach Stealth 700 Gen 2',
                'description' => '50mm NanoclearTM speakers, 20-hour battery, Superhuman Hearing, Bluetooth + 2.4GHz for multi-platform.',
                'price'       => 149.99,
                'rating'      => 4.3,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'Philips SHB3075',
                'description' => 'Wireless Bluetooth 4.1 headset, 12-hour battery, foldable design, integrated mic and echo cancellation.',
                'price'       => 49.99,
                'rating'      => 3.9,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'EPOS H3PRO Hybrid',
                'description' => 'Closed acoustic gaming headset, Bluetooth + 2.4GHz, Active ANC, 25-hour battery and broadcast mic.',
                'price'       => 279.00,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Headphones & Headsets',
                'name'        => 'Creative SXFI Air C',
                'description' => 'Super X-Fi holographic audio, USB-C, custom ear mapping app, 24-hour battery and Bluetooth.',
                'price'       => 129.99,
                'rating'      => 4.2,
            ],

            // ── Battery Chargers ──────────────────────────────────────────
            [
                'category'    => 'Battery Chargers',
                'name'        => 'Anker 747 GaN II 150W',
                'description' => 'All-in-one 4-port charger, 2× USB-C 100W + 2× USB-A, foldable prongs and supports PD 3.0.',
                'price'       => 85.99,
                'rating'      => 4.8,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'Ugreen Nexode 65W GaN Charger',
                'description' => 'Compact 3-port GaN charger, 65W USB-C + 2 USB-A, simultaneous fast charge for 3 devices.',
                'price'       => 45.99,
                'rating'      => 4.7,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'Baseus 120W GaN5 Pro',
                'description' => '6-port desktop charger, 2× USB-C 100W, 3× USB-A 30W, LED display and PPS/PD 3.0 support.',
                'price'       => 79.99,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'ZENDURE SuperPort S4 100W',
                'description' => '4-port GaN charger, 100W total output, auto-detect PD, SurgePad and CellUlar Pro tech.',
                'price'       => 59.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'RAVPower 90W 4-Port Desktop Charger',
                'description' => 'iSmart 2.0 technology, 90W total, 2× USB-C PD + 2× USB-A, universal voltage 100–240V.',
                'price'       => 49.99,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'Belkin BoostCharge Pro 3-in-1',
                'description' => 'Charges iPhone, Apple Watch and AirPods simultaneously, 15W MagSafe compatible wireless pad.',
                'price'       => 149.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'Apple 35W Dual USB-C Compact Power Adapter',
                'description' => 'Dual USB-C ports, 35W total, ultra-compact foldable design, charges iPhone and MacBook simultaneously.',
                'price'       => 59.00,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'Samsung 45W USB-C Super Fast Charger',
                'description' => 'Adaptive Fast Charging 2.0, 45W USB-C PD, compact design and universal voltage 100–240V.',
                'price'       => 39.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'Aukey PA-B7 100W Charger',
                'description' => 'Ultra-compact 100W USB-C GaN charger with Dynamic Detect, foldable prongs and PD 3.0.',
                'price'       => 49.99,
                'rating'      => 4.6,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'Satechi 108W Pro USB-C PD Charger',
                'description' => '3-port USB-C desktop charger, 108W total, charges 3 USB-C devices simultaneously with PD 3.0.',
                'price'       => 99.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'VOLTME 65W Revo Slim GaN Charger',
                'description' => 'Slimmest 65W dual USB-C charger, smart power distribution, foldable prongs and PowerIQ 4.0.',
                'price'       => 34.99,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'Spigen ArcStation Pro 45W',
                'description' => '2-port GaN charger, 45W USB-C PD + 12W USB-A, compact folding plug and dual port simultaneous.',
                'price'       => 29.99,
                'rating'      => 4.3,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'ESR HaloLock 3-in-1 Wireless Charger',
                'description' => 'MagSafe-compatible 3-in-1 pad, 15W phone + Watch + earbuds, foldable for travel and LED indicator.',
                'price'       => 49.99,
                'rating'      => 4.3,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'INIU 65W USB-C Wall Charger',
                'description' => '3-port GaN charger, 65W USB-C + 2 USB-A, PowerIQ 3.0, foldable prongs and LED indicator.',
                'price'       => 27.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'Mophie Speedport 120W GaN Charging Station',
                'description' => '6-device charging station, 2× USB-C 100W, 4× USB-A, desktop design and surge protection.',
                'price'       => 129.95,
                'rating'      => 4.4,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'LENTION 4-in-1 USB-C Hub with 65W PD',
                'description' => 'Foldable travel charger with 65W USB-C PD, 2× USB-A 18W and SD/microSD card reader.',
                'price'       => 39.99,
                'rating'      => 4.2,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'Nekteck PD 60W USB-C Wall Charger',
                'description' => 'GaN USB-C wall charger, 60W Power Delivery, compatible with MacBook Air/Pro, iPad and Galaxy.',
                'price'       => 22.99,
                'rating'      => 4.3,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'CHOETECH 90W USB-C Laptop Charger',
                'description' => '90W PD USB-C desktop charger, 1.5m cable included, universal compatibility and safety certified.',
                'price'       => 35.99,
                'rating'      => 4.2,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'Hyphen-X 100W GaN Charger 4-Port',
                'description' => '100W total GaN wall charger, 2× USB-C PD + 2× USB-A, compact travel design, PPS support.',
                'price'       => 42.99,
                'rating'      => 4.5,
            ],
            [
                'category'    => 'Battery Chargers',
                'name'        => 'Tomtoc 65W 4-Port Power Strip',
                'description' => 'Desktop power strip with 65W USB-C PD, 3× USB-A, 3× AC outlets and 5ft braided cable.',
                'price'       => 54.99,
                'rating'      => 4.4,
            ],
        ];
    }
}
